# Generated by Django 5.1.7 on 2025-04-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_eventmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='metadata',
            field=models.CharField(max_length=255),
        ),
    ]
